name: Auto Deploy to Netlify

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install necessary packages
        working-directory: ./client
        run: npm install
      - name: Build the project
        working-directory: ./client
        run: CI=false npm run build
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
